### PR TITLE
[RAPPS-DB] Add MultiMC 0.7.0-3813

### PR DESCRIPTION
**Pull request by wilsontulus**
MultiMC is a custom launcher for Minecraft that allows you to have multiple, cleanly separated instances of Minecraft with a simple and powerful interface.

Version: 0.7.0-3813
Official Site: https://multimc.org/
GitHub: https://github.com/multimc/launcher
License: Mixed with Apache 2.0 and MS-PL, other components use their own licenses (e.g. Qt5 uses LGPLv2.1)
Test Video (a bit older around 2.5 weeks ago but still works): https://youtu.be/ohrzkZ-9lAI

Latest screenshot:
image

### CODE REVIEW

**Comment by HBelusca** [comment]
And this launcher can indeed launch and run those minecraft instances when tested in ROS as well?

**Comment by HBelusca** [comment]
Maybe you can try to see if you could make the screenshot available for RAPPS to show? (other .ini files in the database show examples of this)

**Comment by wilsontulus** [comment]
Okay, let me post the screenshot here so I can include the link as the screenshot (many INIs and TXTs use github's own screenshot hosting too)

**Comment by wilsontulus** [comment]
Mirror server test works fine.
image

**Comment by learn-more** [comment]
Thanks!

**Pull request merged**
