### PR TITLE
[RAPPSDB] update readme.md

### PR DESCRIPTION
**Pull request by kernelbin**
Add description about screenshot and icon field
Delete out-dated CDPath field

### CODE REVIEW

**Review by learn-more — APPROVED** [review]

**Comment by Saibamen** [comment]
Related: https://github.com/reactos/reactos/pull/3108

**Comment by learn-more** [comment]
@Saibamen  please stop with this nonsense

**Comment by Saibamen** [comment]
Why? Yes, he is the author, but this is Open Source project and other people may not know why this change was made...

Think about it like linked issues in JIRA

**Comment by learn-more** [comment]
> Why? Yes, he is the author, but this is Open Source project and other people may not know why this change was made...
> 
> Think about it like linked issues in JIRA

We don't need this extra level of spam, there is enough to do without having to scroll past nonsense.
If you want to discuss this, github is not the platform for that, so next comments about this will be regarded as a continuation of spam.

**Pull request merged**
