### PR TITLE
Create vc2017x86_64run.txt

### PR DESCRIPTION
**Pull request by blackcrack**
for make modern Programs to run
with vb2017-x86_64

### CODE REVIEW

**Comment by sanchaez** [comment]
Does it work in ReactOS? Same for #10.

**Comment by sanchaez** [comment]
@blackcrack there is no such thing as ROS64 yet, so there is no need for x64 executables right now.

**Comment by blackcrack** [comment]
but it is coming .. 
https://reactos.org/getbuilds/

best regards
Blacky

**Comment by HBelusca** [comment]
what I see coming is x86 only.

**Comment by blackcrack** [comment]
Hi Hermes :)
i have deleted and good .. 
well.. how ever ..
best regards
Blacky

**Comment by blackcrack** [comment]
https://github.com/reactos/reactos/pull/361

you must be blind .. (not bad meant, more friendly)

something named "work together" 
if make a pull request bad !
-=>Super<=- 

if you want , can you reopen this one ..
*A shake of the head(oh boy..)*

**Comment by blackcrack** [comment]
https://github.com/reactos/reactos/pull/361

**Pull request closed without merging**
