### PR TITLE
[RAPPS-DB] Podcast Easy for RAPPS (update)

### PR DESCRIPTION
**Pull request by r57zone**
Update to latest version

### CODE REVIEW

**Comment by sanchaez** [comment]
Hi @r57zone !
Does this work on ReactOS?
Also, [general contribution rules](https://github.com/reactos/reactos/blob/master/CONTRIBUTING.md) still apply here, so you edit your commit message and author information accordingly.

**Comment by r57zone** [comment]
He worked in the past revisions, but then stopped, perhaps after the Wine Staging-Sync earn.

**Comment by r57zone** [comment]
The program has already been tested and added by Daniel Reimer. The new commit is just an update of the version.

Source code - https://github.com/r57zone/Podcast-Easy-for-Windows

Could you make commit it right?
[podcasteasy.txt](https://github.com/reactos/rapps-db/files/1628632/podcasteasy.txt)

**Comment by sanchaez** [comment]
@r57zone I can't, simply because I don't know your real name :) 
Use `git commit --amend --author "Your Name <you@your.email>"` on this branch and do `git push --force` to update the pull request.

**Comment by r57zone** [comment]
My name is Alexander Sivenkov

**Pull request closed without merging**
