### PR TITLE
Create grafx2.txt

### PR DESCRIPTION
**Pull request by alexmyczko**

### CODE REVIEW

**Comment by alexmyczko** [comment]
grafx2-reactos

**Comment by blackcrack** [comment]
some program for Win for create asci-gui's with ansi escape colouring as batch for Terminal/Ssh sessions, would be cool ;)

**Comment by learn-more** [comment]
Hello,
Thanks for your interest in ReactOS!
We ask our contributors [to use their full name when committing](https://github.com/reactos/reactos/blob/master/CONTRIBUTING.md#rules-and-recommendations).
[Please amend your commit with your full name](https://stackoverflow.com/a/3042512), and update this PR.

Regards,

**Comment by alexmyczko** [comment]
I'll try to do that, looking for a document describing how to do it with the github web interface only

**Pull request merged**
