### PR TITLE
updated download link in jdk8.txt

### PR DESCRIPTION
**Pull request by qbancoffee**
changed

URLDownload = https://cdn.azul.com/zulu/bin/zulu8.48.0.53-ca-jdk8.0.265-win_i686.msi
to
URLDownload = http://cdn.azul.com/zulu/bin/zulu8.48.0.53-ca-jdk8.0.265-win_i686.msi

For whatever reason the Applications Manager will not download this file, however if I click on the link at the bottom of the applications manager and it
opens a browser and downloads the file. I can even download it with wget.
I modified
C:\Documents and Settings\Administrator\Local Settings\Application Data\rapps\rapps\jdk8.txt

and replaced "https" with "http" and it downloads and installs correctly.

 Might be an SSL thing, who knows.

### CODE REVIEW

**Comment by learn-more** [comment]
Anything in the log?

**Comment by qbancoffee** [comment]
I can't seem to find a log for the applications manager but maybe I'm looking in the wrong place, where would I find it?

**Comment by learn-more** [comment]
The normal debug log (com port)

**Comment by qbancoffee** [comment]
Ah, That didn't occur to me.

Anyhow, it seems it has to do with security encryption, "ECDSA_P256"
Here is a snippet ftom my capture.


[zulu8.log](https://github.com/reactos/rapps-db/files/5219944/zulu8.log)
(ntoskrnl/ex/sysinfo.c:927) Process B434E2D0 (mscorsvw.exe:0000030C) is a zombie
(ntoskrnl/ex/sysinfo.c:927) Process B434E2D0 (mscorsvw.exe:0000030C) is a zombie
(ntoskrnl/ex/sysinfo.c:927) Process B434E2D0 (mscorsvw.exe:0000030C) is a zombie
(ntoskrnl/ex/sysinfo.c:927) Process B434E2D0 (mscorsvw.exe:0000030C) is a zombie
(ntoskrnl/ex/sysinfo.c:927) Process B434E2D0 (mscorsvw.exe:0000030C) is a zombie
(ntoskrnl/ex/sysinfo.c:927) Process B434E2D0 (mscorsvw.exe:0000030C) is a zombie
(ntoskrnl/ex/sysinfo.c:927) Process B434E2D0 (mscorsvw.exe:0000030C) is a zombie
(ntoskrnl/ex/sysinfo.c:927) Process B434E2D0 (mscorsvw.exe:0000030C) is a zombie
err:(dll/win32/secur32/wine/ntlm.c:2060) ntlm_auth was not found or is outdated. Make sure that ntlm_auth >= 3.0.23 is in your path. Usually, you can find it in the winbind package of your distribution.
fixme:(dll/win32/bcrypt/bcrypt_main.c:356) algorithm L"ECDSA_P256" not supported
err:(win32ss/user/user32/windows/messagebox.c:1048) MessageBox: L"Unable to download the package! Check Internet Connection!"
(drivers/ksfilter/swenum/swenum.c:314) SwDispatchCreate 0
(drivers/ksfilter/ks/swenum.c:1927) KsServiceBusEnumCreateRequest IRP B479C008 Name \{cd171de3-69e5-11d2-b56d-0000f8754380}&{9b365890-165f-11d0-a195-0020afd156e4}
(drivers/ksfilter/swenum/swenum.c:328) SwDispatchCreate 104
(ntoskrnl/ex/sysinfo.c:927) Process B434E2D0 (mscorsvw.exe:0000030C) is a zombie
(ntoskrnl/ex/sysinfo.c:927) Process B434E2D0 (mscorsvw.exe:0000030C) is a zombie
(ntoskrnl/ex/sysinfo.c:927) Process B434E2D0 (mscorsvw.exe:0000030C) is a zombie
(ntoskrnl/ex/sysinfo.c:927) Process B434E2D0 (mscorsvw.exe:0000030C) is a zombie
(win32ss/user/ntuser/nonclient.c:1133) err: Wnd is active and not set active!
(ntoskrnl/ex/sysinfo.c:927) Process B434E2D0 (mscorsvw.exe:0000030C) is a zombie

**Comment by qbancoffee** [comment]
I've been reading about ECDSA and it seems that it's a relatively new scheme. I also skimmed through  "dll/win32/bcrypt/bcrypt_main.c" and "dll/win32/secur32/wine/ntlm.c" but I saw no reference to ECDSA.

I don't know much about about Windows internals and the encryption stuff is rather confusing but given that I don't see a reference to ECDSA and that the target here is Windows server 2003(so ECDSA didn't exist then), is it safe to assume it isn't implemented and it will not be implemented?

If so, is this a good enough reason to allow http instead of https for this download link?
Is this something that might be considered a core bug in ReactOS and thus should be filed?

**Comment by learn-more** [comment]
https://jira.reactos.org/browse/CORE-14198
This should be fixed.

**Comment by qbancoffee** [comment]
O.K., now I see it's the exact same issue. 

I ran rapps.exe under wine configured for Windows 2003 and I was able to download and install jdk8 and notepad++ just fine.

**Comment by learn-more** [comment]
Thanks!

**Pull request merged**
