### PR TITLE
[RAPPS-DB] CORE-14168 Firefox 48.0.2

### PR DESCRIPTION
**Pull request by Getequ**

### CODE REVIEW

**Comment by sanchaez** [comment]
Hi @Getequ !
Have you tested FF 48.0.2 on ReactOS?

**Comment by Getequ** [comment]
@sanchaez  of course! i write it in a jira task version 0.4.8 from 30.12.2017 but it works at least on version 01.01.2017

**Comment by Getequ** [comment]
@JoachimHenze i fixed your comments

**Comment by JoachimHenze** [comment]
Thank you Getequ for your contributions. Good to go now!

**Pull request merged**
