### PR TITLE
Update fileoptimizer.ico

### PR DESCRIPTION
**Pull request by marjuanm**
Reupload file icon, the last is corrupted?

### CODE REVIEW

**Comment by marjuanm** [comment]
Please reupload this icon file, Rapps show this message in log file to try show fileoptimizer app:

fixme:(dll/win32/usp10/opentype.c:1262)   TODO: subtype 1 (Simple context glyph substitution)
err:(win32ss/user/user32/windows/cursoricon.c:539) Corrupted icon file?.
err:(win32ss/user/user32/windows/cursoricon.c:539) Corrupted icon file?.
err:(win32ss/user/user32/windows/cursoricon.c:224) Cannot yet display PNG icons
err:(win32ss/user/user32/windows/cursoricon.c:1426) Failing File is 
    'C:\Documents and Settings\Administrator\Local Settings\Application Data\RApps\appdb\icons\fileoptimizer.ico'.
err:(win32ss/user/user32/windows/cursoricon.c:224) Cannot yet display PNG icons
err:(win32ss/user/user32/windows/cursoricon.c:1426) Failing File is 
    'C:\Documents and Settings\Administrator\Local Settings\Application Data\RApps\appdb\icons\fileoptimizer.ico'.

I send the file icon again, greetings to everyone.

**Comment by katahiromz** [comment]
Cannot yet display PNG icons

**Comment by marjuanm** [comment]
Yes @katahiromz, sorry, I send the file in correct format again.

**Review by JoachimHenze — CHANGES_REQUESTED** [review]
Only touch it, if you can provide a compatible icon for now. Your current proposal is not.

**Comment by marjuanm** [comment]
@JoachimHenze How? I have uploaded the fileoptimizer.ico file to the icons folder again. I have already verified that it is indeed an ico file and not a png file (which was the previous case when the fileoptimizer app was registered in rapps).

**Comment by learn-more** [comment]
This still looks like a png file renamed to .ico

**Comment by marjuanm** [comment]
Yes, well, it was really a 32x32 png converted to ico with https://convertico.com/, but I tried with https://filehelper.com/ and in the file details it tells me:

File Properties
Name:
fileoptimizer.ico
MIME type:
image/x-icon
Size:
2KB
Modified:
Aug 11, 2024, 8:50 p.m.
Image Width:
32px
ImageHeight:
32px

With any other png image the result would be:

Name:
alf.png
MIME type:
image/png

I also tried with https://jumpshare.com/viewer/ico and if the image uploaded in ico it displays it, otherwise if it is a png we will get the error:

Whoops! Not the Right Type of File
This viewer only supports ICO files. The PNG file format you tried to upload is supported by a different viewer.

So, according to me, the icon has been created correctly and is the one I attached in this request. Should I generate the ico file in another way that passes the test?

Greetings, thank you.

**Comment by learn-more** [comment]
> Yes, well, it was really a 32x32 png converted to ico with https://convertico.com/, but I tried with https://filehelper.com/ and in the file details it tells me:
> 
> File Properties Name: fileoptimizer.ico MIME type: image/x-icon Size: 2KB Modified: Aug 11, 2024, 8:50 p.m. Image Width: 32px ImageHeight: 32px
> 
> With any other png image the result would be:
> 
> Name: alf.png MIME type: image/png
> 
> I also tried with https://jumpshare.com/viewer/ico and if the image uploaded in ico it displays it, otherwise if it is a png we will get the error:
> 
> Whoops! Not the Right Type of File This viewer only supports ICO files. The PNG file format you tried to upload is supported by a different viewer.
> 
> So, according to me, the icon has been created correctly and is the one I attached in this request. Should I generate the ico file in another way that passes the test?
> 
> Greetings, thank you.

```
$ file fileoptimizer\(1\).ico
fileoptimizer(1).ico: MS Windows icon resource - 1 icon, 32x32 with PNG image data, 32 x 32, 8-bit/color RGBA, non-interlaced, 32 bits/pixel
```
This is a png-encoded icon, which is invalid in this case.

**Comment by marjuanm** [comment]
Ok @learn-more, what do you recommend to upload the correct icon and apply the same in future application uploads to Rapps?

**Comment by learn-more** [comment]
> Ok @learn-more, I have extracted the installer icon using "IconsExtract" from NirSoft, but the only icon it extracts measures 128x128 pixels. It seems to me that 32x32 are needed here, right?

That is a tad big indeed, but there are more icons like that, so as long as ReactOS can display it that would be fine with me.

**Comment by marjuanm** [comment]
Ready, I have re-uploaded the ico file in 128x128, it was extracted directly from the FileOptimizer installer exe.

**Comment by learn-more** [comment]
Thanks for your contribution!

**Comment by marjuanm** [comment]
Thanks!!!!

**Pull request merged**
