### PR TITLE
[RAPPS-DB] Add Fileoptimizer

### PR DESCRIPTION
**Pull request by marjuanm**
FileOptimizer is an application to reduce unnecessary weight of files, I have only tested it on image files and it works very well in Reactos.

### CODE REVIEW

**Comment by marjuanm** [comment]
I'm adding some screenshots of FileOptimizer running in Reactos.
Screenshot_1
Screenshot_2
Screenshot_3
Screenshot_4

**Comment by marjuanm** [comment]
Before and after compressing the graphic files, as we see, the weight of the file has been reduced a little without damaging the image or causing it to lose its quality.
before
after

**Review by JoachimHenze — APPROVED** [review]
Approved. I will merge it in a week if nobody will merge it earlier than that.

**Review by learn-more — APPROVED** [review]

**Comment by marjuanm** [comment]
thanks @JoachimHenze JoachimHenze

**Pull request merged**
