### PR TITLE
Fixes some HTTPS URLS

### PR DESCRIPTION
**Pull request by KyleKatarn31**
7zip, Abiword site URL should use HTTPS, not HTTP

### CODE REVIEW

**Comment by learn-more** [comment]
Did you test the downloads in reactos?

**Comment by KyleKatarn31** [comment]
Since HTTPS URLS are legit and seems some other products are already using HTTPS url for download, what could be the issue ? Any specific precaution or guidance ?

**Comment by learn-more** [comment]
> Since HTTPS URLS are legit and seems some other products are already using HTTPS url for download, what could be the issue ? Any specific precaution or guidance ?

Our ssl support is not on the same level as for win10.

**Comment by KyleKatarn31** [comment]
Any specific procedure to test a local RAPPS DB ?

**Comment by Swyter** [comment]
The files are check-summed with SHA-1. So validation is not a big issue here.
The only thing you gain with TLS in rapps is that people won't know the exact file you are downloading.

**Comment by KyleKatarn31** [comment]
My suggestion is more on site URL, not necessarily on download url (see suggested changes)

**Comment by learn-more** [comment]
> My suggestion is more on site URL, not necessarily on download url (see suggested changes)

and yet you change them.
Either check that they work in reactos, or revert it.

**Pull request merged**
