### PR TITLE
Add/update Turkish translations

### PR DESCRIPTION
**Pull request by eersoy93**
Add and/or Update Turkish translations of RAPPS entries. This is work in progress currently.

### CODE REVIEW

**Comment by GeoB99** [comment]
If you still intend to work on it please mark this pull request as a draft for the time being.

**Comment by eersoy93** [comment]
These changes can be merged.

**Comment by eersoy93** [comment]
I'll complete adding/updating the translations.

**Comment by katahiromz** [comment]
This branch has conflicts that must be resolved

**Comment by Neustradamus** [comment]
Dear @eersoy93, @learn-more, @archeYR, @ColinFinck, @dreimer1986, @AmineKhaldi, @HeisSpiter, @cgutman,

Can you update the UltraVNC version and add https in links?

Currently it very old and unsecure:
- https://github.com/reactos/rapps-db/blob/master/ultravnc.txt

Thanks in advance.

**Pull request merged**
