### PR TITLE
Add new apps: MuseScore, MySql, Photivo and USBDeView.

### PR DESCRIPTION
**Pull request by AS383**
Add new apps: MuseScore, MySql, Photivo and USBDeView (with Russian translation).

### CODE REVIEW

**Comment by learn-more** [comment]
You tested all of them?

**Comment by AS383** [comment]
Yes, I test all some time ago. If wanted I can retest with current version and populate results to wiki. 
...@mail.ru is not intentional. I think it would be resolved to normal login, but it does not.

**Comment by learn-more** [comment]
@AS383 I truncated the first part of the email, because if it was not your intention to use this email address, it would still show up in the history of the comments here.
You can inspect the full email address here: https://github.com/reactos/rapps-db/commit/562105ab3380f64b9a7a812952e2443c06e813ad.patch

**Comment by AS383** [comment]
@learn-more Thanks for hint. Can I avoid including e-mail in future?
Also I found sha1 sum of USB Deview is wrong. Please exclude it from the pull.

**Comment by sanchaez** [comment]
@AS383 we currently require contributions with both your name and _real_ email. Tell us if you wish to use another address.

**Comment by learn-more** [comment]
@AS383 We need some email, if you do not want to use your public one you can have github create a masked one for you.
To update your existing commits:
https://stackoverflow.com/a/1320317

**Comment by AS383** [comment]
I does not want to specify another address. It ok to use current as public for any contributions lists. Thanks everybody for support :)

**Pull request merged**
