### PR TITLE
Add Rainmeter and Internet Download Manager (IDM)

### PR DESCRIPTION
**Pull request by xmha97**
# Screenshots
## Rainmeter
Rainmeter on ReactOS
## Internet Download Manager (IDM)
IDM on ReactOS

### CODE REVIEW

**Comment by xmha97** [comment]
cc:
@learn-more
@katahiromz

**Comment by xmha97** [comment]
cc: @katahiromz

**Comment by learn-more** [comment]
cc: @xmha97

**Comment by xmha97** [comment]
> 
> 
> cc: @xmha97

What should I do to merge this pull request?

**Comment by learn-more** [comment]
Thanks for your contribution, sorry for the delay

**Pull request merged**
