### PR TITLE
Add Simple Database to rapps please

### PR DESCRIPTION
**Pull request by faradey8951**
Simple Database, ported from Windows and fully working. Need to be installed .NET Framework 4.0
Some screenshots

### CODE REVIEW

**Comment by learn-more** [comment]
What is the purpose of this application?
This is not a database, it is some data written in zip files.

Furthermore, if you send usernames and passwords to yourself with your own email, do not include the username and password of your mail account in the setup.

Last, but not least: this file downloads a file from your github, which it will execute if found...

**Comment by blackcrack** [comment]
@faradey8951 you could create a DB-Editor of the existent and downloaded RAPPS database
(so the whole single files) where it is to make possible for make a bundle for other Peoples to have a possible for updating the own db with other Software and links, as example:
The user have include other extra programs (free,Osource,share,card and so on) in his Program-db entered (with your Rapps-DB-AppEditor* where it is able to collecting creating standard-textfiles with Sections and maintaining the whole) with checkboxes could it maybe selected and compress the textfiles as a zip (a.e.  name-creationday-version-architercture1-architecture2-architecture3.rappsdb[zip]) and inside be the db-textfiles where be in able to add the actual db to make it able also go in and edit the single textfiles again for manual updating.
The Other Datas could you take out of the urlDownload*² textfild and the [test] Button could download the File and check all important other entrys, as example SHA1(md5 maybe too)

Maybe could you add more as 1 single Download possible, as example
urlDownload1=
urlDownload2=
urlDownload3=
urlDownload4=

to have the possible for comparison of the files and 
to be secure to be able the program download in any case
maybe up to 100Mirror possibility's on the one or other
it's maybe still online, this have prove and let show in the past to be every to have more as one mirror, with this it is able too for downgrading .. maybe check all files and collecting older versions
with a checkbox..
And load the App-folder local on the Sambaserver (a.e.: //linuxserver/windows/Filemanagement/totalcmd/packs-installer

read in the File/setup-package the Program,... ,... ,version, sha1 and create automatical App-db-entry-single-files for each exe file.
Therewith could it possible to collecting local on the Workstation or from the Server whe whole programs.
With the collectingname-date.rappsdb[zip] can it be able also to store setup-file inside and use the CDpath= as internal path like CDpath=./setupfile.exe therewith could earch setup in file.exe and folder stored in the collectingname-date-version.rappsdb[zip] so 2files or a file/a folder ,
as example [7zip.txt](https://github.com/reactos/rapps-db/blob/master/7zip.txt) + 7z1805.exe+7z1805-x64.exe
in 7zip-23.10.2018-18.05-x86-x64.rappsdb[zip] (so, both files in it x86&x64 and maybe also ARM if exist)
```
Totalcommander-Listerplugin:
c:\bearbeit\bearbeit\7z1805.exe
on Microsoft Windows Seven x64 Professional Edition Version 6.1 (build 7601) Service pack 1 
File Version Information : 
Version language : Englisch (USA)
      CompanyName	: Igor Pavlov
      FileDescription	: 7-Zip Installer
      FileVersion	: 18.05
      InternalName	: 7zipInstall
      LegalCopyright	: Copyright (c) 1999-2018 Igor Pavlov
      OriginalFilename	: 7zipInstall.exe
      ProductName	: 7-Zip
      ProductVersion	: 18.05
Creation Date	: 23/10/2018  09:22:43 
Last Modif. Date	: 23/10/2018  09:22:34 
Last Access Date	: 23/10/2018  09:22:34 
FileSize	: 1181017 bytes ( 1153.337 KB,  1.126 MB ) 
FileVersionInfoSize	: 1444 bytes  
File type	: Application (0x1) 
Target OS	: Win32 API (Windows NT) (0x40004) 
File/Product version	: 18.5.0.0 / 18.5.0.0
Language 	: Englisch (USA) (0x409) 
Character Set	: 1200 (ANSI - Unicode (BMP of ISO 10646)) (0x4B0) 
Build Information : 
Debug Version	: no 
Patched Version	: no 
Prerelease Version	: no 
Private Version	: no 
Special Build	: no 
``` 


*Administration the Rapps-Application DB as Administrator, creating the single textfiles files as a editor where gives the whole a standard and a frame for all with textfilds/boxes [Section(0)] Name, Version,License,Description e.t.z/a.s.o./и т. д. the Description could be binded with an Yandex&google&other-Translater and the most same entrys could auto-included on the other Language Textfild, as example, вы пишете на русском языке в русском поле, а авто-переводчик затем записывает в другие поля на соответствующем языке.
therewith could it able for any one to create an Program-entry in any language and the autor, need to write the description in his own entry and the Program could recognize the empty fields and could fill that with the respective language on the Internation Description Textfilds.

*² urlSite, sha1 and the Size(in byte and MB) could the program automatic
including by checking the download-file, so the urlDownload of the File, the program could check out
the urldownload and setting up automatically the Size and sha1 by downloading, check out the file(also setupfiles, the version, size, Buildingdate and so on..) and delete the file if all Data's collecting and push in the textiles.

How you can may Start,
1. create a Window, where Listing all textfiles from the local-admin-folder of rapps,
make it possible for test the file, create a new file, delete a file and Import a *.rappsdb file (download/extract the setupfiles and store it on rapps-download (you can set it and create a new standard {configurable}), Export (download and compress the files+app-text-file) as %Appname%-%appcreatindate%-%version%-%arch1%-%arch2%-%arch3%~.rappsdb

2.Integrate infozip.dll for collecting and compressing , why not 7zip, zip is the fundamental in general
and zip is using in WinNT and it is supporting, also by open the pack ans install, you save many time and work later and maybe can you take the zip-algorithm of WinNT=> Reactos.. zip is integrated ...

3.Make checkboxes for selecting before the apps for make it able to edit, delete or exporting
in single Processing-Windows for each App / Files as/in app and exporting and compress in .rappsdb[zip]

and the next way can you be creative,
i have give you easy a suggestion/idea about what's could be if you want..
To founding the wheel new it's unnecessary, so, work what you have and this
in the Administrator account the rapps-db is existent .

the zipped .rappsdb can you setting up as standard .. and at last, can you distribute 
it as extra single program who works also in MSWinNT ;)

maybe can you add winvers=95-98 and winntvers=5.1-6.2 therewith could it meant in which windows-Versions run this program.. so Reactos 5.1 ? This is also very important for collecting the whole programs for using later in the future times for programs in the past..

With Your program, if you make it Comptatible to Win95 could also collecting Programs
from the past of the Win95's times and trade it again via your .rappsdb[zip] packages..
if it is possible for some program to exist before WinNt times.. therewith could with .rappsdb building a new sharing-community , maybe exist old programs on old stored harddisk's ;)
and in the rappsdb zip's could be other helping files too , like nfo :) Well...

Rapps-DB-AppEditor could be a great App... and if you not in able to name it Rapps-DB-AppEditor
could it named maybe Ra**bbs**-DB-AppEditor ;) (BulletinBoardSerice-File ....) uploading by a filehoster the exported rappsdb file ;) .. or rabbsdb ... Therewith can you programming not only for Reactos, nope, for all WinNT-version who exist.. and maby as extra.. support for Win95-ME (win98se and so on too)

best and kindly regards
с наилучшими пожеланиями
Blacky

**Comment by faradey8951** [comment]
Thank you ))))

**Comment by blackcrack** [comment]
@faradey8951 
if you have build up something, let me know on my mail  blackcrack with blackysgate.de 
i want also test it a bit :) Rapps have a connector to the apps-server and have a Variable
for setting up the way to Admins rapps-Repos, may the program can check if there something or not,
if not, may can your program download the repos in the right folder and be in able to create
in the admin account this folder and download from the orginal rapps-repos the textfiles ..
these be only my thoughts .. maybe had you the same :)
and it is maybe able to build up a 2nd Application server, at your side anywhere .. in a free webhoster with ftp-connect for a programming in connecting-login in your program for upload and download text-files and give other programmers also a possible for maintaining .. the rappsdb-files could upload on ftp-providers with a direct downloadlink in the textfile, because the most programs be not huge and with plug ins for upload ... and there in germany gives filehoster with 100-150 Gig (i know, there be providers with more space in TB and PB but at first should it makeable for the private user)  and with the time could to crystallize out who is greatest and most consistent, it can grow and become very stable for a long time and the future to hold the files .. maybe something like a torrent, but over ftp for store and fastest download .. and maybe also a linuxserver-software to be in able for add a service from the own filestore for all and the Provider could it also supporting with a rappsstore to store the textfiles and the rappsdb[zip] files with the whole versions .. therewith could it also possiblefor the huge providers to supporting something with an own plugin+ in the plugin _one_ adversiting-popup for pay the space (no sex, no bad things, only clean adversing (it will settle by itself anyway/It's going to be self-regulating anyway ) ) maybe something as example .. and only one advertising by Program instance this keep within hold this limits, because how many users could use this program.. by the way, i have tell Jaix the suggestion of rapps and he speak about in the irc, it's comes from Mandrakes rpmdrake.. as info between us.. ;) oky, so, mail me if you have a binary i'll be happy to try out  :)

**Comment by learn-more** [comment]
@blackcrack  you have been warned before to stop with the rambling on github.

**Pull request closed without merging**
