### PR TITLE
[RAPPS-DB] Add Git for Windows 2.10.0

### PR DESCRIPTION
**Pull request by binarymaster**
Add Git for Windows 2.10.0, because ReactOS now can! :smile: 

CORE-12931

### CODE REVIEW

**Comment by HBelusca** [comment]
Why does the diff say "binary file"?

Also, MinTTY (for Git Bash) exhibits some .... "peculiar" problems.

**Comment by binarymaster** [comment]
> Why does the diff say "binary file"?

Hmm... UCS-2 LE encoding, how I got it there... :thinking:

**Comment by binarymaster** [comment]
@HBelusca I've fixed encoding.

**Comment by Mouvedia** [comment]
The latest version, as of today, is 2.17.1; is it compatible as well?

**Comment by gigaherz** [comment]
Any version newer than 2.10.0 requires NT6. Our forward compatiblity system is not that good just yet.

**Comment by Mouvedia** [comment]
@gigaherz thanks, I didn't know.

There's at least [some demand](https://groups.google.com/forum/#!topic/git-for-windows/TUP9uK_oUNM) of backport fixes for the 2 critical vulnerabilities.

**Comment by HBelusca** [comment]
Oh by the way...
... could you also add TortoiseGit to the RAPPS list? The latest version that works on WinXP/2k3 is:
https://download.tortoisegit.org/tgit/1.8.16.0/
I've tested it on last ROS 0.4.10-dev and it works great so far! :)

**Comment by sanchaez** [comment]
@HBelusca I believe you can add that yourself :relaxed:

**Comment by HBelusca** [comment]
Done (see #30)

**Pull request merged**
