### PR TITLE
[RAPPS-DB] Add A game with a kitty 3 (agwak)

### PR DESCRIPTION
**Pull request by marjuanm**
Please add this game to rapps, this game works perfectly on Reactos with the sound also works properly.

### CODE REVIEW

**Comment by marjuanm** [comment]
Screenshots from the game running on Reactos
screenshot01
Screenshot02
Screenshot03
Screenshot04
Screenshot05

**Review by learn-more — APPROVED** [review]

**Comment by marjuanm** [comment]
I think I made a mistake here, I uploaded the icon file in png format instead of .ico, should I change it?

**Comment by learn-more** [comment]
> I think I made a mistake here, I uploaded the icon file in png format instead of .ico, should I change it?

Yes please

**Comment by marjuanm** [comment]
Done...

**Review by learn-more — APPROVED** [review]

**Comment by learn-more** [comment]
Thanks for your contribution!

**Comment by marjuanm** [comment]
Thanks!!!

**Pull request merged**
