### PR TITLE
Create protracker.txt

### PR DESCRIPTION
**Pull request by alexmyczko**

### CODE REVIEW

**Comment by learn-more** [comment]
Hello,
Thanks for your interest in ReactOS!
We ask our contributors [to use their full name when committing](https://github.com/reactos/reactos/blob/master/CONTRIBUTING.md#rules-and-recommendations).
[Please amend your commit with your full name](https://stackoverflow.com/a/3042512), and update this PR.

Regards,

**Comment by binarymaster** [comment]
It also would be nice to have screenshots confirming this software runs in ReactOS without major issues.

And the same for #21.

**Comment by alexmyczko** [comment]
But this is my real name, and my real email address is also in my gh profile. where would i put the screenshots?

**Comment by learn-more** [comment]
'Alex' does not seem like it is your full name.

**Comment by alexmyczko** [comment]
Alex Myczko?

**Comment by sanchaez** [comment]
@alexmyczko you can Ctrl+V the screenshot right into the comment view, like this (image taken from [EricLPer video](https://www.youtube.com/watch?v=Fyxxcrzxm8A)): 
image

**Comment by alexmyczko** [comment]
protracker keeps crashing on reactos, missing dll

**Comment by learn-more** [comment]
So it does not work?

**Comment by alexmyczko** [comment]
Well I cant really test since rapps db has too old vc libs that protracker in win32 needs

**Comment by archeYR** [comment]
Tested it. No need for any libraries. Works fine after installing VirtualBox guest additions (with 3D acceleration enabled in VM settings). Sound is a bit distorted though, but it can be fixed with lowering priority of protracker in the task manager or replacing portcls with the 2K3 one.
virtualbox_reactos_19_05_2018_02_32_58

**Pull request merged**
