### PR TITLE
[RAPPS-DB] Add Tiny Snake 1.0 (TinySnake)

### PR DESCRIPTION
**Pull request by DosX-dev**
Hello! I added a new game to the database.

### CODE REVIEW

**Comment by katahiromz** [comment]
The automated check is failing.
Please check the red cross.

**Comment by katahiromz** [comment]
Thanks. We want your legal full name and e-mail address. Some GitHub and commit settings are required.

Can you read this article?

https://github.com/reactos/reactos/blob/master/CONTRIBUTING.md#rules-and-recommendations

**Comment by DosX-dev** [comment]
Kay Kokh, collab@kay-software.ru

**Comment by katahiromz** [comment]
https://github.com/reactos/reactos/blob/master/CONTRIBUTING.md#rules-and-recommendations

**Comment by DosX-dev** [comment]
Ok! I'll do everything according to the instructions soon. Please wait.

**Comment by DosX-dev** [comment]
I set my full name and indicated my email for cooperation in the required field. You can check it :)

**Comment by DosX-dev** [comment]
Gameplay video
https://github.com/reactos/rapps-db/assets/117774904/0fa08fc7-b216-4343-a1c3-56ee08da4bb0

**Comment by katahiromz** [comment]
Then, commit author setting.

https://reactos.org/wiki/ReactOS_Git_For_Dummies#Amending_your_commit_with_name.2FE-mail

**Comment by DosX-dev** [comment]
The instructions were quite confusing, but I seemed to do everything that was required. If this is not the case, tell me what to change. ¯\_(ツ)_/¯

**Comment by binarymaster** [comment]
Full name is not a requirement for rapps-db pull requests.

**Review by learn-more — APPROVED** [review]

**Review by JoachimHenze — APPROVED** [review]
3.5kb executable? Respect! Approved to express my appreciation.

**Pull request merged**
