### PR TITLE
Create PlopBootManager.txt

### PR DESCRIPTION
**Pull request by x0rh**
I request to add Plop Boot Manager to RApps cause it is important to have it installed on a real HDD with ReactOS in order to boot (in old machines) for example ReactOS LiveUSB (vgal buils for now) and GNU/Linux distro to recover debugging logs when ReactOS access is impossible.

virtualbox_reactosplopbootmanagerbootmenu

virtualbox_reactosfat32plopbootmanager2

### CODE REVIEW

**Comment by learn-more** [comment]
Please stick to one account Quim.

**Comment by x0rh** [comment]
There is plop boot manager 
and the patch that makes possible to install Plop in freelrd.ini . 2 files to be downloaded.
I request feedback.

**Comment by x0rh** [comment]
PR closed? 
Well I´ll do the same PR later.... I assume you are busy with the first 2 PRs.

**Comment by x0rh** [comment]
Is mandatory to use real names? 
According to the following comment on matermost is optional:


hbeluscacomment

**Comment by blackcrack** [comment]
@x0rh 
+1  , Rapps-DB have nothing to do with Reactos-Code, it's a collecting of Programms
and should in trust of the users, is this not giveing and the User PR only his Factory or use a Factory the Rapps-DB only for Advertising/Spam, should the User/Spambot and Factory kicked out !
and by the way, where it is in the wiki to must be Realnames ?
https://reactos.org/wiki/ReactOS_Git_For_Dummies
There is something from Username and not from Realnames !
Username can also be a Alias .

best regards
Blacky

Realname+Maintaining Programs=BullS.. imho !

**Pull request closed without merging**
