### PR TITLE
Update npp.txt

### PR DESCRIPTION
**Pull request by marcinszynkowski**
Updated link for notepad++ download.
Right now the link provided is not available. It causes the rapps to show an error message about download error.
I've updated it to version available on the notepad++ official website.

### CODE REVIEW

**Comment by learn-more** [comment]
Did you test this version in ReactOS ?

**Comment by marcinszynkowski** [comment]
> Did you test this version in ReactOS ?

It's lower version than 6.9.2 that it was in the database - I assume that it worked, the available is 6.9.
But to be sure, I will test this version. I will update when finish.

**Comment by marcinszynkowski** [comment]
rosnpp
It works, I've tested it.

**Comment by JoachimHenze** [comment]
I think the version chosen by marcinszynkowski is ok.
Starting with v7.0 Notepad++ updater GUP.exe depends
on a libcurl.dll which is compiled for Vista+ (unnecessarily).

**Comment by marcinszynkowski** [comment]
> You forgot to update version value.
> 
> ```diff
> -Version = 6.9.2
> +Version = 6.9
> ```

Thank you for spotting a mistake. 
I've fixed that :)

**Pull request merged**
