### PR TITLE
Add a game with a kitty 3 to rapps

### PR DESCRIPTION
**Pull request by marjuanm**
Please add this game (A game with a Kitty 3) to the Reactos app base. It works without problems in Reactos, it has sound and it can also be heard without problems.

### CODE REVIEW

**Comment by marjuanm** [comment]
I attach several screeenshot to this game running on Reactos.
screenshot01
Screenshot02
Screenshot03
Screenshot04
Screenshot05

**Comment by JoachimHenze** [comment]
image

**Comment by marjuanm** [comment]
Why are the commits marked as invalid? Are they carried out without problems in my fork?
image

**Comment by JoachimHenze** [comment]
try adding an additional newline at the last line for example.

**Comment by marjuanm** [comment]
> try adding an additional newline at the last line for example.

Thanks!!!!!
image

**Comment by marjuanm** [comment]
image
Please ignore this, it was part of the PR of my previous commit, on my local fork it still appeared as unresolved. I'm still a newbie to Github.

**Pull request closed without merging**
