### PR TITLE
[RAPPS-DB] Add PCSX to RAPPS

### PR DESCRIPTION
**Pull request by shytzedaka**
PCSX works on ReactOS:

image

image
https://www.youtube.com/watch?v=NSK0dzAbbAU&feature=youtu.be

Ready to be merged!

### CODE REVIEW

**Comment by HBelusca** [comment]
No idea whether it could be better to upload that to archive.org (in case it's ok to do so....)?

**Comment by shytzedaka** [comment]
> No idea whether it could be better to upload that to archive.org (in case it's ok to do so....)?

I could yea

**Comment by shytzedaka** [comment]
> No idea whether it could be better to upload that to archive.org (in case it's ok to do so....)?

@HBelusca Kinda got banned from archive.org though. This URL should work right? we have other .txt files using github links in RAPPS

**Comment by HBelusca** [comment]
> > No idea whether it could be better to upload that to archive.org (in case it's ok to do so....)?
> 
> @HBelusca Kinda got banned from archive.org though. This URL should work right? we have other .txt files using github links in RAPPS

LOL OK I think it should be fine then...

**Comment by HBelusca** [comment]
Maybe you can add some link to the website of PCSX (and also mention that it's free & open-source program, according to what I've seen...)

**Comment by shytzedaka** [comment]
> Maybe you can add some link to the website of PCSX (and also mention that it's free & open-source program, according to what I've seen...)

Their website is Down. PCSX.net now they have PCSX2.net but that is something different.

**Comment by HBelusca** [comment]
oh.... ok; I was looking at https://www.emuparadise.me/Sony_Playstation_Emulators/Windows/PCSX/18 instead.

**Pull request merged**
