### PR TITLE
[RAPPS-DB] Created a readme

### PR DESCRIPTION
**Pull request by BenNottelling**
Follow up to https://github.com/reactos/rapps-db/pull/71
Based off the same file there, but removed some info that wasn't relevant to this database. This is a markdown readme
At some point it would be a good idea to talk about the kinds of downloads RAPPS can't handle, but I'm not 100% what kinds it has issues with

Use[ this link](https://github.com/reactos/rapps-db/blob/9b95e06218f32331ab643c9be8113f2f82fe5c3f/readme.md) to preview it

### CODE REVIEW

**Comment by katahiromz** [comment]
Rename it as `README.md`. Uppercase is the better.

**Comment by BenNottelling** [comment]
> Rename it as `README.md`. Uppercase is the better.

I tried to rename it but git didn't track it as a change, so instead I did a forcepush. Seems the PR hasn't updated, but you can clearly see it here
https://github.com/BenNottelling/rapps-db/commit/f4dbeeefdca5f4382bce6b75ec5170bdcd748c00

**Comment by katahiromz** [comment]
Once try another name.

**Comment by BenNottelling** [comment]
I think github just hasn't noticed the change like git, but I'm assuming it would be fixed upon a merge

**Pull request merged**
