### PR TITLE
[TRANSLATION] Add Traditional Chinese translation

### PR DESCRIPTION
**Pull request by eason329**
##  Purpose
Adds Traditional Chinese localization for programs.

##  Proposed Changes
- Adds Chinese Traditional localization for programs
> Progress: Done except some program I may forgot to translate or not intended to use in this language

- Sort translation in ascending order by Locale ID

### CODE REVIEW

**Comment by learn-more** [comment]
Why did you move other languages around?

**Comment by eason329** [comment]
> Why did you move other languages around?

Some languages' translation (Yes I mean _that_ neutral Spanish) do not follow the Locale ID order and I got mad during the translation process. So I sorted them in ascending order. Hope you guys don't mind.

**Comment by eason329** [comment]
Now cc @reactos/lang-chinese for review

**Review by njlyf2011 — APPROVED** [review]

**Comment by eason329** [comment]
15 Oct 2022 Update:

I have reverted some file (i.e. xbgpack1.txt) as they are pending deletion.

And please consider to merge this PR if no more problem.

**Review by binarymaster — APPROVED** [review]

**Pull request merged**
